---
kind: pipeline
type: docker
name: sx-ci

trigger:
  branch:
    - master
  event:
    - push
    - tag
    - pull_request

clone:
  depth: 1

steps:
  - name: lint
    image: golangci/golangci-lint:v1.39.0-alpine
    volumes:
      - name: deps
        path: /go
    commands:
      - apk add libpcap-dev libc-dev linux-headers
      - golangci-lint run -v
      # go 1.16 install doesn't modify go.mod and go.sum
      - go install github.com/mgechev/revive@v1.0.3
      - revive -config .revive.toml -formatter friendly ./...

  - name: test & build
    image: golang:1.16-alpine
    volumes:
      - name: deps
        path: /go
    commands:
      - apk add libpcap-dev libc-dev gcc linux-headers
      - go test ./... -v -cover
      - go build -ldflags "-w -s"

  - name: goreleaser-snapshot
    image: golang:1.16-alpine
    volumes:
      - name: deps
        path: /go
    commands:
      - apk add libpcap-dev libc-dev gcc linux-headers curl git
      - curl -s https://raw.githubusercontent.com/goreleaser/get/master/get > goreleaser.sh
      - chmod +x goreleaser.sh && ./goreleaser.sh --snapshot
    when:
      event: push

volumes:
  - name: deps
    temp: {}

---
kind: pipeline
type: docker
name: release

depends_on:
  - sx-ci

trigger:
  branch:
    - master
  event:
    - tag

clone:
  depth: 1

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags

  - name: release
    image: golang:1.16-alpine
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add libpcap-dev libc-dev gcc linux-headers curl git
      - curl -s https://raw.githubusercontent.com/goreleaser/get/master/get | sh

